;;; themes/guts-theme.el -*- lexical-binding: t; -*-

(deftheme guts "A theme inspired by Guts from Berserk - dark, gray, with hints of red.")

(let ((background "#282828")
      (foreground "#e4e4e4")
      (cursor "#fdfdfd")
      (border "#3C3C3C")
      (black "#1b1b1b")
      (red "#ff6655")
      (green "#99bb66")
      (yellow "#e0c080")
      (blue "#88aaff")
      (magenta "#bb88dd")
      (cyan "#66bbcc")
      (white "#dddddd")
      (bright-black "#555555")
      (bright-red "#ff9999")
      (bright-green "#ddffbb")
      (bright-yellow "#ffeebb")
      (bright-blue "#bbddff")
      (bright-magenta "#eebbff")
      (bright-cyan "#99eeff")
      (bright-white "#ffffff"))

  (custom-theme-set-faces
   'guts
   `(default ((t (:background ,background :foreground ,foreground))))
   `(cursor ((t (:background ,cursor))))
   `(fringe ((t (:background ,background))))
   `(mode-line ((t (:foreground ,foreground :background ,black))))
   `(region ((t (:background ,bright-black))))
   `(highlight ((t (:background ,bright-black))))
   `(success ((t (:foreground ,green))))
   `(warning ((t (:foreground ,yellow))))
   `(error ((t (:foreground ,red :weight bold))))
   ;; Syntax highlighting
   `(font-lock-builtin-face ((t (:foreground ,magenta))))
   `(font-lock-comment-face ((t (:foreground ,bright-black))))
   `(font-lock-function-name-face ((t (:foreground ,blue))))
   `(font-lock-keyword-face ((t (:foreground ,red))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,yellow))))
   `(font-lock-variable-name-face ((t (:foreground ,cyan))))
   `(font-lock-constant-face ((t (:foreground ,magenta))))
   `(font-lock-warning-face ((t (:foreground ,bright-red :weight bold))))
   ))

(provide-theme 'guts)
